name: Test

on: [push]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: test
        run: |
          yarn install
          yarn test
        env:
          CI: true
          NOVE_ENV: test
